#!/bin/zsh

# exit when a command fails
set -e
echo "\n********* COMPILATION START **********\n"

mkdir -p bin

cc -dynamiclib lib.c -o ./bin/lib.dylib
# you can just link with the dylib immediately
# cc bin/lib.dylib main.c -o bin/main && ./bin/main
cc main.c -o bin/main && ./bin/main